name: Build

env:
  # enable colored output
  PY_COLORS: 1

on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed
    branches:
      - main

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  docker:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    permissions:
      contents: read
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.workflow_run.head_sha }}

    # - name: Set up QEMU
    #   uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: false
        tags: nexus-aggregator:latest
        platforms: linux/amd64
        cache-from: type=gha
        cache-to: type=gha,mode=max
        load: true

    - name: Test Docker image
      run: docker run --rm nexus-aggregator:latest uv run pytest --cov=src --cov-report=xml --cov-report=term-missing

    - name: Scan Docker image for vulnerabilities
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'nexus-aggregator:latest'
        format: 'table'

    # TODO: Добавить загрузку результатов в GitHub Security tab когда настроишь права
    # - name: Scan Docker image for vulnerabilities (SARIF)
    #   uses: aquasecurity/trivy-action@master
    #   with:
    #     image-ref: 'nexus-aggregator:latest'
    #     format: 'sarif'
    #     output: 'trivy-results.sarif'
    #   continue-on-error: true
    #
    # - name: Upload Trivy scan results to GitHub Security tab
    #   uses: github/codeql-action/upload-sarif@v3
    #   if: ${{ hashFiles('trivy-results.sarif') != '' }}
    #   with:
    #     sarif_file: 'trivy-results.sarif'
    #   continue-on-error: true
